# Generated by Django 6.0 on 2025-12-24 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_learning', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cours',
            name='image',
        ),
        migrations.AddField(
            model_name='cours',
            name='fichier',
            field=models.FileField(blank=True, null=True, upload_to='cours/'),
        ),
    ]
