# Generated by Django 6.0 on 2025-12-25 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_learning', '0002_remove_cours_image_cours_fichier'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='couverture',
            field=models.ImageField(blank=True, help_text='Image de couverture du cours', null=True, upload_to='couvertures/'),
        ),
    ]
