# Generated by Django 5.0.7 on 2025-12-25 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_learning', '0003_cours_couverture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cours',
            name='couverture',
        ),
        migrations.AddField(
            model_name='cours',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cours_images/'),
        ),
    ]
